# core/os/modules/terminal-ui.nix
{
  pkgs,
  lib,
  config,
  ...
}:

let
  inherit (config.nixpi) primaryUser;
  terminalCfg = config.nixpi.terminal;
  zellijCfg = terminalCfg.zellij;
  primaryHome = "/home/${primaryUser}";
  sessionName = "nixpi-${config.networking.hostName}-${primaryUser}";
  selectedZellij =
    if zellijCfg.packageMode == "nixpkgs" then
      pkgs.zellij
    else
      throw "nixpi.terminal.zellij.packageMode = native-patched is reserved for a later in-repo package implementation";
  generatedConfig = pkgs.writeText "nixpi-zellij-config.kdl" ''
    // Generated by NixPI.
    default_layout "${zellijCfg.piLayout.name}"
    session_name "${sessionName}"
    attach_to_session ${if zellijCfg.attachExistingSession then "true" else "false"}
    on_force_close "detach"
    pane_frames true
    simplified_ui false
  '';
  generatedLayout = pkgs.writeText "nixpi-zellij-layout-${zellijCfg.piLayout.name}.kdl" ''
    layout {
      default_tab_template {
        pane size=1 borderless=true {
          plugin location="zellij:tab-bar"
        }
        children
        pane size=2 borderless=true {
          plugin location="zellij:status-bar"
        }
      }
      tab name="Pi" focus=true {
        pane command="pi"
      }
      tab name="Shell" {
        pane
      }
    }
  '';
  launcher = pkgs.writeShellScriptBin "nixpi-launch-terminal-ui" ''
    # Default bypass env var remains NIXPI_NO_ZELLIJ unless overridden.
    set -euo pipefail

    bypass_env_var='${zellijCfg.bypassEnvVar}'
    session_type=tty
    if [ -n "''${SSH_CONNECTION:-}" ] || [ -n "''${SSH_TTY:-}" ]; then
      session_type=ssh
    fi

    allowed_session_types=' ${lib.concatStringsSep " " zellijCfg.autoStartOn} '
    if [[ "$allowed_session_types" != *" $session_type "* ]]; then
      decision='skip:session-type'
    elif [ -n "''${ZELLIJ:-}" ]; then
      decision='skip:already-in-zellij'
    elif [ -n "''${!bypass_env_var:-}" ]; then
      decision='skip:bypass'
    else
      decision='launch'
    fi

    if [ "''${NIXPI_TERMINAL_UI_TEST:-0}" = '1' ]; then
      printf '%s\n' "$decision"
      exit 0
    fi

    if [ "$decision" != 'launch' ]; then
      exit 0
    fi

    export ZELLIJ_AUTO_EXIT='${if zellijCfg.exitShellOnExit then "true" else "false"}'
    export ZELLIJ_CONFIG_FILE='${generatedConfig}'

    if ! ${lib.getExe selectedZellij} --config ${lib.escapeShellArg generatedConfig} --layout ${lib.escapeShellArg generatedLayout}; then
      printf '%s\n' 'nixpi: failed to launch Zellij, continuing with plain shell.' >&2
      exit 0
    fi
  '';
in
{
  imports = [ ./options.nix ];

  config = lib.mkIf (terminalCfg.interface == "zellij" && zellijCfg.enable) {
    environment.systemPackages = [
      selectedZellij
      launcher
    ];

    systemd.tmpfiles.settings.nixpi-zellij = {
      "${primaryHome}/.config".d = {
        mode = "0755";
        user = primaryUser;
        group = primaryUser;
      };
      "${primaryHome}/.config/zellij".d = {
        mode = "0755";
        user = primaryUser;
        group = primaryUser;
      };
      "${primaryHome}/.config/zellij/layouts".d = {
        mode = "0755";
        user = primaryUser;
        group = primaryUser;
      };
      "${primaryHome}/.config/zellij/config.kdl"."L+" = {
        argument = "${generatedConfig}";
      };
      "${primaryHome}/.config/zellij/layouts/${zellijCfg.piLayout.name}.kdl"."L+" = {
        argument = "${generatedLayout}";
      };
    };
  };
}
