{ lib, nixPiModulesNoShell, piAgent, appPackage, setupApplyPackage, mkTestFilesystems, mkManagedUserConfig, ... }:

let
  initSystemFlake = ../../core/scripts/nixpi-init-system-flake.sh;
in
{
  name = "nixpi-system-flake";

  nodes.machine =
    { ... }:
    {
      imports = nixPiModulesNoShell ++ [
        mkTestFilesystems
      ];
      _module.args = { inherit piAgent appPackage setupApplyPackage; };

      networking.hostName = "system-flake-test";
      system.stateVersion = "25.05";

      environment.etc."system-flake-marker".text = "preserved";
      environment.etc."nixos/configuration.nix".text = ''
        { ... }:
        {
          networking.hostName = "system-flake-test";
        }
      '';
      environment.etc."nixos/hardware-configuration.nix".text = ''
        { ... }:
        {}
      '';

    }
    // (mkManagedUserConfig { username = "pi"; });

  testScript = ''
    machine = machines[0]
    nixpkgs_url = "path:/tmp/host-nixpkgs"
    stable_release = "25.11"

    machine.start()
    machine.wait_for_unit("multi-user.target", timeout=300)

    machine.succeed("test -f /etc/system-flake-marker")
    machine.succeed("grep -q 'preserved' /etc/system-flake-marker")
    machine.succeed("/run/current-system/sw/bin/bash ${initSystemFlake} /srv/nixpi system-flake-test pi UTC us")
    machine.succeed("test -f /etc/nixos/flake.nix")
    machine.fail("test -e /etc/nixos/nixpi-integration.nix")
    machine.fail("test -e /etc/nixos/nixpi-host.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'networking.hostName = \"system-flake-test\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.fail("grep -q '/channels/nixos' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixos-unstable' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixpi-integration.nix' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixpi-host.nix' /etc/nixos/flake.nix")

    machine.succeed("printf '%s\n' '# Generated by NixPI bootstrap' '{' '  description = \"NixPI system flake\";' '  inputs = {' '    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";' '    nixpi.url = \"path:/srv/nixpi\";' '  };' '}' > /etc/nixos/flake.nix")
    machine.succeed("/run/current-system/sw/bin/bash ${initSystemFlake} /srv/nixpi system-flake-test pi UTC us")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixos-unstable' /etc/nixos/flake.nix")

    machine.succeed("rm -f /etc/nixos/flake.nix")
    machine.succeed("env NIXPI_NIXPKGS_FLAKE_URL='" + nixpkgs_url + "' /run/current-system/sw/bin/bash ${initSystemFlake} /srv/nixpi system-flake-test pi UTC us")
    machine.succeed("grep -q '" + nixpkgs_url + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.succeed("test -f /etc/system-flake-marker")
    machine.succeed("grep -q 'preserved' /etc/system-flake-marker")

    print("nixpi-system-flake test passed!")
  '';
}
