{ lib, nixPiModulesNoShell, piAgent, appPackage, setupApplyPackage, mkTestFilesystems, mkManagedUserConfig, ... }:

{
  name = "nixpi-host-owned-flake";

  nodes.machine =
    { ... }:
    {
      imports = nixPiModulesNoShell ++ [
        ../../core/os/modules/firstboot
        mkTestFilesystems
      ];
      _module.args = { inherit piAgent appPackage setupApplyPackage; };

      networking.hostName = "host-owned-test";
      system.stateVersion = "25.05";

      environment.etc."host-owned-marker".text = "preserved";

    }
    // (mkManagedUserConfig { username = "pi"; });

  testScript = ''
    machine = machines[0]
    nixpkgs_url = "path:/tmp/host-nixpkgs"
    stable_release = "25.11"

    machine.start()
    machine.wait_for_unit("multi-user.target", timeout=300)

    machine.succeed("test -f /etc/host-owned-marker")
    machine.succeed("grep -q 'preserved' /etc/host-owned-marker")
    machine.succeed("nixpi-bootstrap write-host-nix host-owned-test pi UTC us")
    machine.succeed("test -f /etc/nixos/flake.nix")
    machine.succeed("test -f /etc/nixos/nixpi-integration.nix")
    machine.succeed("grep -q 'host-owned-test' /etc/nixos/nixpi-host.nix")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.fail("grep -q '/channels/nixos' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixos-unstable' /etc/nixos/flake.nix")

    machine.succeed("printf '%s\n' '# Generated by NixPI bootstrap' '{' '  description = \"Host-owned NixOS flake with NixPI layered on top\";' '  inputs = {' '    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";' '    nixpi.url = \"path:/srv/nixpi\";' '  };' '}' > /etc/nixos/flake.nix")
    machine.succeed("nixpi-bootstrap write-host-nix host-owned-test pi UTC us")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.fail("grep -q 'nixos-unstable' /etc/nixos/flake.nix")

    machine.succeed("rm -f /etc/nixos/flake.nix")
    machine.succeed("env NIXPI_NIXPKGS_FLAKE_URL='" + nixpkgs_url + "' nixpi-bootstrap write-host-nix host-owned-test pi UTC us")
    machine.succeed("grep -q '" + nixpkgs_url + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("test -f /etc/host-owned-marker")
    machine.succeed("grep -q 'preserved' /etc/host-owned-marker")

    print("nixpi-host-owned-flake test passed!")
  '';
}
