d /run/bloom 0770 bloom bloom -
d /var/lib/bloom 0755 bloom bloom -
d /var/lib/bloom/.pi 0755 bloom bloom -
d /var/lib/bloom/.pi/agent 0755 bloom bloom -
d /var/lib/bloom/Garden 0755 bloom bloom -
d /var/lib/bloom/.bloom 0755 bloom bloom -
d /var/lib/bloom/.config 0755 bloom bloom -
d /var/lib/bloom/.config/gh 0700 bloom bloom -
d /var/lib/bloom/.config/containers 0755 bloom bloom -
d /var/lib/bloom/.config/containers/systemd 0755 bloom bloom -
d /var/lib/bloom/media 0755 bloom bloom -
C /var/lib/bloom/.pi/agent/settings.json 0644 bloom bloom - /usr/local/share/bloom/.pi/agent/settings.json
C /var/lib/bloom/.bashrc 0644 bloom bloom - /usr/local/share/bloom/skel/.bashrc
C /var/lib/bloom/.bash_profile 0644 bloom bloom - /usr/local/share/bloom/skel/.bash_profile

# Additional /var content from installed system packages
L /var/lib/unbound/root.key - - - - ../../../etc/unbound/dnssec-root.key
d /var/lib/unbound 0755 unbound unbound -
d /var/lib/geoclue 0755 geoclue geoclue -
d /var/cache/libX11 0755 root root -
d /var/cache/libX11/compose 0755 root root -
