d /var/lib/bloom 0755 bloom bloom -
d /var/lib/bloom/.pi 0755 bloom bloom -
d /var/lib/bloom/.pi/agent 0755 bloom bloom -
d /var/lib/bloom/Garden 0755 bloom bloom -
d /var/lib/bloom/.bloom 0755 bloom bloom -
C /var/lib/bloom/.pi/agent/settings.json 0644 bloom bloom - /usr/local/share/bloom/.pi/agent/settings.json
C /var/lib/bloom/.bashrc 0644 bloom bloom - /usr/local/share/bloom/skel/.bashrc
C /var/lib/bloom/.bash_profile 0644 bloom bloom - /usr/local/share/bloom/skel/.bash_profile
