version: 1
source_repo: https://github.com/pibloom/pi-bloom
services:
  matrix:
    version: "0.1.0"
    category: communication
    image: forgejo.ellis.link/continuwuation/continuwuity:0.5.0-rc.6
    optional: false
    preflight:
      commands: [podman, systemctl]
  element:
    version: "0.1.0"
    category: communication
    image: localhost/bloom-element:latest
    optional: false
    depends: [matrix]
    preflight:
      commands: [podman, systemctl]
  dufs:
    version: "0.1.0"
    category: sync
    image: docker.io/sigoden/dufs:v0.38.0
    optional: false
    preflight:
      commands: [podman, systemctl]
  code-server:
    version: "0.1.0"
    category: development
    image: localhost/bloom-code-server:latest
    optional: true
    preflight:
      commands: [podman, systemctl]
